name: Vavoo Playlist Update

on:
  workflow_dispatch: # Permette l'avvio manuale
  schedule:
    # Esegue lo script ogni 3 ore (00:00, 03:00, 06:00, ecc.)
    - cron: '0 */3 * * *'

jobs:
  update_files:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Skript ausführen
        run: python export_script.py

      - name: Änderungen speichern und hochladen
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          ls -lh
          
          git add vavoo_all.m3u vavoo_full.json
          
          # Il messaggio di commit includerà ora l'orario preciso dell'aggiornamento
          git commit -m "Automatisches Update: $(date +'%d.%m.%Y %H:%M')" || echo "Keine Änderungen gefunden"
          
          git push origin main
